# Generated by Django 5.1.4 on 2024-12-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='branch',
            new_name='Branch',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='section',
            new_name='Section',
        ),
        migrations.AlterModelTable(
            name='studentprofile',
            table='attendance_studentprofile',
        ),
    ]
